image: debian

packages:
  - python3
  - python3-virtualenv

sources:
  - https://git.sr.ht/~jmstover/ps3iso

tasks:
  - setup: |
      virtualenv venv
      source venv/bin/activate
      pip install -r requirements.txt -r requirements-dev.txt
      python -V
  - build: |
      make test

