image: debian/stable

packages:
  - curl
  - python3
  - python3-virtualenv
  - python3-setuptools
  - genisoimage

sources:
  - https://git.sr.ht/~jmstover/ps3iso

secrets:
  - 553a1730-f7ae-47a8-8bea-207728ea1aec

tasks:
  - setup: |
      cd ps3iso
      python3 -m virtualenv -p python3 venv
      source venv/bin/activate
      python -V
      pip install -q -r requirements-dev.txt
  - test: |
      cd ps3iso
      source venv/bin/activate
      make test
  - doc: |
      cd ps3iso
      source venv/bin/activate
      make doc
      [ ! -x ~/.rtd-hook ] || ~/.rtd-hook

